language: node_js
node_js:
- "node"
cache: npm
script: 
- npm test
- npm run deploy
after_script: npm run alias
env:
  global:
    secure: yfp6HM8G2vwGhfB298KjnyQkmUi7yqUPjvqKxBThDOAyeRt1pNuvsnUyAdHM/uJxwrcIWQ6326crn9xjZg2EZGyEt0D18efpBw/Ck4F91i88g6wbT6BaNUzLGGi4N0yxtiw9vfMD4HTZtYZQbE1eeUQ7eKwwV6Wv//kfVQ7TPQBtY4gMKYpUA5dO4nDo2zOMfR6nNVW2FOKepJ1McXKKEl264z/wGcfLnP24lu5ibKf8fvj1mdusr6qUJDEV689ODbMDQOCNfdG/JcKHUD4cE513+eUpTjOdW83Znd1HnmHNO+QDZcLnocAhxgchTzw3kYEpkxFpmMMPLJWRchFiD1BGVKczJUG4C++Hm5XDGOQpSGYV2i8cNggJBgy4jUQ8XoQ2UBqlC1cRLkuA5h2lbbmLWmsFBPZk6zIalROxoDHV/C9FbJ+wqDHePmw+erySdSlSz/Or6p5lif7HEdzm9Tk31SN02TDRrypCdPO4YmwIcRfZPnq0Xa3bEYnUG91hBV1klOvURWmwJcbqNZ7VdXWxZ149m4pVPbiT5XGOtzpeanBVm7NoedrQKo/XeTHdA3KiMGSAn+5KjOLSuQ9ZHaUT6NkiFJHjVB1tmyxaO2M9YT259nj7UB+YPZUG9g6WxDVoHNkasivX/UR1EYbLxEmWw9W5oQUamsU/3Sk6ciY=
